In [6]:
import numpy as np

In [7]:
a=np.array([[1,2,3,3,1],[6,8,11,10,7]])
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [8]:
At=a.transpose()
At

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [9]:
mean_a=np.array([np.mean(a[0]), np.mean(a[1])])
mean_a

array([2. , 8.4])

In [10]:
a_centered=At-mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [11]:
b_centered=a_centered.transpose()
a_centered_sp=b_centered[0] @ b_centered[1]
a_centered_sp/(len(a_centered)-1)

2.0

In [16]:
cov_a=np.cov(a)
cov_a[0][1]

2.0